name: Check translations
on:
  pull_request:
    paths-ignore:
      - "**.py"

jobs:
  check-translations:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "check-translations not required"'
