name: Run code quality checks
on:
  pull_request:
    paths:
      - '**.py'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PDM
        run: curl -sSL https://pdm-project.org/install-pdm.py | python3 - -v 2.16.1 -p /usr/local
      - name: Install dependencies
        run: pdm install -d
      - name: Run linters
        run: pdm lint
