name: Run unit tests
on:
  pull_request:
    paths:
      - '**.py'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: 'Run unit tests'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.12'
          pdm-version: '2.16.1'
      - name: Install dependencies
        run: pdm install -d
      - name: Run linters
        run: pdm test
